import { ApiActions } from './api.actions';

const ApiStatusStore = {};

// API State Reducer
// API state is automatically generated by api.http.service 
export function ApiStatusReducer(state:any = ApiStatusStore, { type, payload }:any) {
	//console.log('STORE REDUCER: ApiStatusReducer', type, payload);

	switch (type) {

		// Reset State
		case ApiActions.RESET:
			return ApiStatusStore;

		// State change
		case ApiActions.STATE_CHANGE:
			state[payload.apiMap.storeProperty] = { ...state[payload.apiMap.storeProperty], ...payload.newState };
			break;

		// Reset API errors
		case ApiActions.RESET_ERRORS:
			Object.keys(state).forEach(key => {
				state[key].modifyError = false;
				state[key] = { ...state[key] };
			});
			break;

		// Reset API errors
		case ApiActions.RESET_SUCCESS:
			Object.keys(state).forEach(key => {
				state[key].modified = false;
				state[key] = { ...state[key] };
			});
			break;
	}
	
	return state;
}
