"use strict";
var __assign = (this && this.__assign) || Object.assign || function(t) {
    for (var s, i = 1, n = arguments.length; i < n; i++) {
        s = arguments[i];
        for (var p in s) if (Object.prototype.hasOwnProperty.call(s, p))
            t[p] = s[p];
    }
    return t;
};
exports.__esModule = true;
var api_actions_1 = require("./api.actions");
var ApiStatusStore = {};
// API State Reducer
// API state is automatically generated by api.http.service 
function ApiStatusReducer(state, _a) {
    //console.log('STORE REDUCER: ApiStatusReducer', type, payload);
    if (state === void 0) { state = ApiStatusStore; }
    var type = _a.type, payload = _a.payload;
    switch (type) {
        // Reset State
        case api_actions_1.ApiActions.RESET:
            return ApiStatusStore;
        // State change
        case api_actions_1.ApiActions.STATE_CHANGE:
            state[payload.apiMap.storeProperty] = __assign({}, state[payload.apiMap.storeProperty], payload.newState);
            break;
        // Reset API errors
        case api_actions_1.ApiActions.RESET_ERRORS:
            Object.keys(state).forEach(function (key) {
                state[key].modifyError = false;
                state[key] = __assign({}, state[key]);
            });
            break;
        // Reset API errors
        case api_actions_1.ApiActions.RESET_SUCCESS:
            Object.keys(state).forEach(function (key) {
                state[key].modified = false;
                state[key] = __assign({}, state[key]);
            });
            break;
    }
    return state;
}
exports.ApiStatusReducer = ApiStatusReducer;
